[colors.primary]
background = "0x191724"
foreground = "0xe0def4"

[colors.normal]
black = "0x26233a"
red = "0xeb6f92"
green = "0x31748f"
yellow = "0xf6c177"
blue = "0x9ccfd8"
magenta = "0xc4a7e7"
cyan = "0xebbcba"
white = "0xe0def4"

[colors.bright]
black = "0x6e6a86"
red = "0xeb6f92"
green = "0x31748f"
yellow = "0xf6c177"
blue = "0x9ccfd8"
magenta = "0xc4a7e7"
cyan = "0xebbcba"
white = "0xe0def4"
